config/routes.rb
Rails.application.routes.draw do
  resources :clients
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'dashboards#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys:[:email, :password, :password_confirmation, :current_password, :first_name, :last_name, :country, :address, :phone, :bio, :occupation, :state, :avatar
      ])
    end
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :password, :password_confirmation, :current_password, :first_name, :last_name, :country, :address, :phone, :bio, :occupation, :state, :avatar
        ])
      end

      private
      def layout_by_resource
        if devise_controller? && resource_name == :user && action_name == 'new'
          "devise"
      elsif devise_controller? && resource_name == :user && action_name == 'edit'
        'application'
      else
        "application"
      end
    end
end

app/controllers/clients_controller.rb
class ClientsController < InheritedResources::Base

  private

    def client_params
      params.require(:client).permit(:name, :email, :request, :job_type, :note, :phone, :country, :user_id)
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for(@client) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :request %>
    <%= f.input :job_type %>
    <%= f.input :note %>
    <%= f.input :phone %>
    <%= f.input :country %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Request</th>
      <th>Job type</th>
      <th>Note</th>
      <th>Phone</th>
      <th>Country</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.email %></td>
        <td><%= client.request %></td>
        <td><%= client.job_type %></td>
        <td><%= client.note %></td>
        <td><%= client.phone %></td>
        <td><%= client.country %></td>
        <td><%= client.user %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Request:</strong>
  <%= @client.request %>
</p>

<p>
  <strong>Job type:</strong>
  <%= @client.job_type %>
</p>

<p>
  <strong>Note:</strong>
  <%= @client.note %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Country:</strong>
  <%= @client.country %>
</p>

<p>
  <strong>User:</strong>
  <%= @client.user %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Streams</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="fix-header fix-sidebar">
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
      <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
    </div>
    <div id="main-wrapper">
      <%= render "shared/header" %>
      <%= render "shared/sidebar" %>
      <div class="page-wrapper">

    <%= yield %>
    <!-- footer -->
    <footer class="footer"> © 2018 All rights reserved. Developed by <a href="https://zonia.co">Zonia Solutions</a></footer>
    <!-- End footer -->
  </div>
  </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Streams:Your All In One Cloud Inventory </title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="keywords" content="Streams All In One Online Inventory For Every User" />
  <meta name="description" content="Streams All In One Online Inventory For Everybody, for marketters, ecommerce, social media infleuncers, portfolio, developers and Enterprise companys, Your helpdesk for customer retention and management better than salesforce and easier to use">
  <meta name="author" content="Fortune Jakes from Zonia Solutions">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script type="applijewelleryion/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

</head>
<body class="fix-header fix-sidebar">

  <div id="main-wrapper">

      <div class="unix-login">
          <div class="container-fluid">
              <div class="row justify-content-center">
                  <div class="col-lg-4">
                      <div class="login-content card">
                          <div class="login-form">

                              <h4>Welcome To Streams</h4>


                              <%= yield %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</body>

app/views/shared/_sidebar.html.erb
<!-- Left Sidebar  -->
<div class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="nav-devider"></li>
                <li class="nav-label">Home</li>
                <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-tachometer"></i><span class="hide-menu">Dashboard <span class="label label-rouded label-primary pull-right">2</span></span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="index.html">Ecommerce </a></li>
                        <li><a href="index1.html">Analytics </a></li>
                    </ul>
                </li>
                <li class="nav-label">Apps</li>
                <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-envelope"></i><span class="hide-menu">Email</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="email-compose.html">Compose</a></li>
                        <li><a href="email-read.html">Read</a></li>
                        <li><a href="email-inbox.html">Inbox</a></li>
                    </ul>
                </li>
                <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-bar-chart"></i><span class="hide-menu">Clients & Requsts</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="chart-flot.html">Clients</a></li>
                        <li><a href="chart-morris.html">Add New Client</a></li>

                    </ul>
                </li>
                <li class="nav-label">Management</li>
                <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-suitcase"></i><span class="hide-menu">Products & Orders <span class="label label-rouded label-warning pull-right">6</span></span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="ui-alert.html">New Product</a></li>
                        <li><a href="ui-button.html">Orders</a></li>
                        <li><a href="ui-dropdown.html">Revenue</a></li>

                    </ul>
                </li>
    <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-suitcase"></i><span class="hide-menu">Projects <span class="label label-rouded label-danger pull-right">6</span></span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="uc-calender.html">Projects</a></li>
                        <li><a href="uc-datamap.html">New Project</a></li>
                        <li><a href="uc-nestedable.html">Tasks</a></li>
                        <li><a href="uc-sweetalert.html">Calendar</a></li>

                    </ul>
                </li>
                <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-wpforms"></i><span class="hide-menu">Social Media</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="form-basic.html">Paid Posts</a></li>
                        <li><a href="form-layout.html">Twitter</a></li>
                        <li><a href="form-validation.html">Facebook</a></li>
                        <li><a href="form-editor.html">Instagram</a></li>
                        <li><a href="form-dropzone.html">Medium</a></li>
                    </ul>
                </li>
                <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-table"></i><span class="hide-menu">Teams</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="table-bootstrap.html">Teams</a></li>
                        <li><a href="table-datatable.html">Add Team Member</a></li>
                    </ul>
                </li>
                <li class="nav-label">Events</li>
                <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-columns"></i><span class="hide-menu">Events</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="layout-blank.html">New Event</a></li>
                        <li><a href="layout-boxed.html">Sehedule</a></li>
                        <li><a href="layout-fix-header.html">Fundraisers</a></li>
                        <li><a href="layout-fix-sidebar.html">Event Manager</a></li>
                    </ul>
                </li>


            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</div>
<!-- End Left Sidebar  -->